### ISSUE TITLE
Add documentation for `Plan` members.

### ISSUE THREAD

**Issue by frankmcsherry** [comnik/declarative-dataflow#13]
The members of 

```rust
pub enum Plan {
    /* members */
}
```

don't have any documentation, and to the extent that they (or their descendants) are the public surface of the query language, they should explain what they each do. I'm happy to take a stab at that!

I have a related goal of making each of them into `struct` types, and attempting to have each of them implement a trait that corresponds to `create_inputs` and `implement_plan`, so that we can break apart i. the set of query operators from ii. the implementation of each query operator. With your blessing, I can take a swing at that at the same time.

**Comment by comnik** [comment]
Sounds good! But I think we shouldn't even consider `create_inputs` part of the contract. As you mention in #9 (I'll get back on that) that should be a separate concern entirely, together with a nice way of accessing globally named collection traces.

I'm also hoping that only `Lookup`, `Entity`, `HasAttr`, etc.. will be required to hook-up a different data model, without affecting the implementation of the other operators, so maybe those should all be defined together within a single trait.

**Comment by comnik** [comment]
Landed in 8d09de282deb5126ba1cda286a006ea6319a282c
