### ISSUE TITLE
Generalize `Register` request

### ISSUE THREAD

**Issue by frankmcsherry** [comnik/declarative-dataflow#14]
What do you think about generalizing the `Register` request, which is currently 

```rust
    Register { query_name: String, plan: Plan, rules: Vec<Rule> },
```

to something like

```rust
    Register { public: Vec<Rule>, private: Vec<Rule> }
```

where the intent is that all rules in `public` are published, and all rules `private` are locally available but not published.

**Comment by comnik** [comment]
Yes, beautiful!

If you want to tackle any of those issues yourself let me know, otherwise I'll get to it over the weekend.

**Comment by frankmcsherry** [comment]
Yup, I'll take a stab (I can't self-assign, but let's imagine I have).

**Comment by comnik** [comment]
Everything seems to work and this is now the new `Register`, as of ef9216f23b04f87ffcec0223782c792053e8bb0f
