### ISSUE TITLE
rustfmt

### ISSUE THREAD

**Issue by li1** [comnik/declarative-dataflow#44]
Run (and keep using) `rustfmt` real soon now 🙃

Edit: Also, think about using `clippy`

**Comment by comnik** [comment]
Initial formatting done in e6ebda4cc814d554b83417841a874274f206f2db.
Not sure whether automated enforcement is necessary right now, given the limited number of contributors.

**Comment by comnik** [comment]
We have a TravisCI setup now which will enforce rustfmt and clippy warnings.
