### ISSUE TITLE
Build errors?

### ISSUE THREAD

**Issue by alex-dixon** [comnik/declarative-dataflow#50]
Fresh clone of repo and `cargo run` using latest stable channel failing with following errors:

```
error[E0599]: no method named `register_source` found for type `declarative_dataflow::server::Server<u64, mio::Token>` in the current scope
   --> src/bin/server.rs:626:60
    |
626 |                                 if let Err(error) = server.register_source(source, scope) {
    |                                                            ^^^^^^^^^^^^^^^
```

```
error[E0599]: no method named `register_sink` found for type `declarative_dataflow::server::Server<u64, mio::Token>` in the current scope
   --> src/bin/server.rs:633:60
    |
633 |                                 if let Err(error) = server.register_sink(req, scope) {
    |                                                            ^^^^^^^^^^^^^

```

Is it just me?

Don't want to lead us down the wrong track but I noticed I have a new Cargo.lock file. I think that means I could have different versions of dependencies?

**Comment by eoxxs** [comment]
Maybe doing a `cargo clean` followed by a `cargo run`?

**Comment by comnik** [comment]
Sorry that is on me, I've been running the server with wall-clock time for experimental purposes (finishing my master's thesis as we speak), but broke normal mode in the process.

If it doesn't matter to you you could try with "--features real-time".

Will fix soon.

**Comment by comnik** [comment]
52d8863ab6ac9d8f535772c2750787f49ed50892

waiting for CI to confirm

**Comment by comnik** [comment]
Travis seems happy, please re-open if it still causes problems on your end.

**Comment by alex-dixon** [comment]
@comnik Fixed, thanks!
