### ISSUE TITLE
Infinite loop in is_any_outdated()

### ISSUE THREAD

**Issue by eoxxs** [comnik/declarative-dataflow#55]
`is_any_outdated()` uses an internal timer which `advance_domain()` changes.
If we probe a Dataflow that has not started or has no current inputs we might run into an infinite loop in the server at : `worker.step_while(|| server.is_any_outdated());`
because we already advanced the inputs but the probe still only sees the "old" timestamps.

**Comment by comnik** [comment]
This should also be addressed by f09ec284248a7cc95d0d26f6292ecb3e38d1482e, again, tests required.

**Comment by comnik** [comment]
Impossible to have an infinite loop, because we step fixed amounts now :)
