### ISSUE TITLE
Named inputs

### ISSUE THREAD

**Issue by comnik** [comnik/declarative-dataflow#9]
Add support for named query inputs and expose additional input handles to them. This would allow to parameterize a registered query without re-registering.

**Comment by frankmcsherry** [comment]
What do you think of the possibility of extending the `Request` enum, which current has 

```rust
enum Request {
    Transact { tx: usize, tx_data: Vec<TxData> },
    Register { query_name: String, plan: Plan, rules: Vec<Rule> },
    // LoadData { filename: String, max_lines: usize },
}
```

to include operations like e.g. 

```rust
CreateInput { input_name: String },
AdvanceInput { input_name: String, time: Time },
CloseInput { input_name: String },
```

This would allow you to break apart the creation of named inputs from the query itself, so that one is expected to create user-manipulable inputs first and build queries out of them second.

In principle, `Transact` could also now come with an input identifier, to name the table/relation that it means to modify (breaking a bit with the global EAV model).

**Comment by frankmcsherry** [comment]
I think you said: all sounds good, except maybe break `Transact` apart further. If so, we totally agree! If not, no rush to re-wire things.

Having separate `AdvanceInput` events would allow people to drive historical collections around if they want (drive them forward, at least). I *think* it would change the intent of the `historical` bit to be "self-advancing", where if it is (isn't?) set toggles whether the trace automatically keeps pace with the current timestamp.

**Comment by comnik** [comment]
Great, then we do indeed agree!

Regarding `AdvanceInput` and historical collections I don't quite follow. Wouldn't user's then also need a way to advance the tuple collection (in a scenario where there is a separate source of tuples, e.g. from a Kafka topic)? Otherwise we'd still have to keep that around forever, wouldn't we?

On that note, there is the new `--enable-history` flag which controls exactly that at the moment. I've noticed that without history, registering a query will not produce outputs for any previously transacted data. If I only `advance` and don't `distinguish` the traces, then everything works as expected. From this I must conclude that my understanding of what is happening within the trace is lacking...

**Comment by comnik** [comment]
In a sense this is now possible, we have `CreateInput` that can be used with both, `Transact` and `AdvanceInput`. We will add a `CloseInput` and be done with it until further notice.
